LocationHelper 추가
mash-up-kr/bottle-flow-android pull request #14
Opened 2018-11-24 20:19 UTC by jujinkim

LocationHelper 추가했습니다 (위치정보 가져오는친구)

+
ApplicationContext를 static으로 얻어오기 위해 App extends한 BottleApp 추가 및 manifest에 추가했는데
이건 이걸로 해도 될지 다같이 얘기한번하는게 좋겠습니다.

어짜피 언젠간 추가되어야 할 것 같긴한데, 이름을 BottleApp으로 해도 될 지?

2018-11-24 20:46 UTC, chaeniiz requested changes

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +        private set
이 친구는 뭘까용 🙂 지워도 되지 않나요? 👀👀

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/BottleApp.kt
> +            private set
이 친구는 뭔가용

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/BottleApp.kt
> +class BottleApp : Application() {
어플리케이션 상속한 이유가 뭐예요~?

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +            mLocationManager!!.removeUpdates(this)
`!!` 는 null일 수 있는 녀석이지만 null이 아니라고 확신한다는 식으로 쓰는 녀석인데요, mLocationManager이 절대 null일 경우가 없는 건가요? 선언은 nullable하게 되어 있어서요~ (`private var mLocationManager: LocationManager? = null`)
만에 하나 null이 들어올 경우에는 앱이 죽을 거예요!

mLocationManager?.let { removeUpdates(this) } 식으로 호출하면 null이 아닐 경우에만 블럭 안의 구문을 처리하는데 이런 식으로 변경해 보는 것도 괜찮을 것 같구용 mLocationManager이 변하는 값이 아니라면 상수로 빼 놓고 null 처리 안 해 줘도 될 것 같아요!

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +
엠티라인 지워 주세용~

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +                    lastLocation!!.latitude,
lastLocation null 들어오는 경우에는 앱이 죽을 거예요. null 아닐 시에만 호출하도록 변경해 주세용!

2018-11-24 20:46 UTC, chaeniiz commented on app/src/main/res/values/strings.xml
> +    <string name="unable_get_locaiton">Cannot get location info.</string>
WOW 영문판까지,,,, 스게,,,,, 👍

2018-11-24 20:47 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/BottleApp.kt
> +class BottleApp : Application() {
static으로 ApplicationContext를 얻어오기 위해 쓰는 android idiom입니다

2018-11-24 21:02 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +        private set
마지막으로 저장된 Location을 직접 가져오고 싶을 경우를 위해 뚫어놓은 API입니다.
(현재 위치정보 얻어오려면 요청 -> GPS신호 -> 콜백 이라는 긴 과정을 거치는데, 당연히 GPS신호를 가져오는데 시간이 오래걸립니다. 필요에 따라 GPS신호를 얻어오는 대신 마지막으로 저장된 위도/경도를 즉시 바로 사용할 일이 있을까 해서 남겨놓았습니다)

ex
지금은 구현되지 않았지만, gps를 과도하게 사용하면 배터리소모가 크므로 뭐 한 10분에 한번씩만 진짜 gps를 얻어오고 그 전에는 lastLocation에 저장된애를 돌려쓴다던지

2018-11-24 21:22 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +            mLocationManager!!.removeUpdates(this)
확인해보니
getSystemService(LOCATION_SERVICE)
얘는 ApplicationContext에서 가져와도 문제 없는 서비스로 보이네요
nullable한 선언 없애고 선언과 동시에 초기화해주는쪽으로 바꾸겠습니다

2018-11-24 21:25 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/BottleApp.kt
> +            private set
ApplicationContext를 static하게 가져오기 위해 Application요소를 static에 박아놓은 친구입니다

2018-11-24 21:26 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +                    lastLocation!!.latitude,
catch에 exception 추가하겠습니다

2018-11-24 21:59 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +        private set
오오 넹넹 ex도 좋은 것 같아여! 그래서 그게 `lastLocation` 에 대한 설명인 거죠?! 저는 `private set` 이게 필요한 놈인가 해서용!!!

2018-11-24 21:59 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +                    lastLocation!!.latitude,
앗 그럼 lastLocation null일 경우 절대 없는 거예염?

2018-11-24 22:04 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +                    lastLocation!!.latitude,
null일 수 있습니다 (이 클래스 사용자가 '최초 위치정보를 요청하기 전'에 '가장 최근의 주소 이름 정보'를 얻어오는 api를 호출 한 경우)

의도한 상황은 아니라서 ?.let{}나 if(~!=null)이 아닌 catch로 뺐습니다.

2018-11-24 22:04 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +        private set
private set이 뭔지 제가 보고올게요

2018-11-24 22:05 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/BottleApp.kt
> +class BottleApp : Application() {
흠 이거 모든 팀원들이 다 이해할 수 있도록 풀어서 설명해 주시면 좋을 것 같아요 ☺️ 일단 네이밍은 `BottleApp` 으로 해 놓읍시당~

2018-11-24 22:16 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +                    lastLocation!!.latitude,
넵 그럼 '최초 위치정보를 요청하기 전'에 '가장 최근의 주소 이름 정보'를 얻어오는 api를 호출 한 경우는 에러의 경우라고 보면 되는 걸까요? 👀 에러 문구 띄워 주는 건 어때요~?

2018-11-24 22:21 UTC, chaeniiz commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +        private set
**getter만 있고 setter는 없는 경우** private set을 쓴다고 합니다! 기억합싀다 모듀들 😎

2018-11-24 22:39 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +                    lastLocation!!.latitude,
플로우 따라가보니 null 안되네요. lateinit으로 바꾸겠습니다.

2018-11-24 22:39 UTC, jujinkim commented on app/src/main/java/com/bottlecap/bottleflow/BottleApp.kt
> +class BottleApp : Application() {
굿

2018-11-24 22:44 UTC, chaeniiz commented
L G T M ! 고생하셨습니다 ☺️👍

2018-11-24 22:45 UTC, merged

2018-11-29 00:54 UTC, eastroots92 commented on app/src/main/java/com/bottlecap/bottleflow/locationHelper/LocationHelper.kt
> +        private set
하나 배워갑니다. 기억하겠습니다